name: store-api

services:

  db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./volume/db:/var/lib/postgresql/data

  account:
    build:
      context: ./pma252.account-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080